version: "3.4"

services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hadoop-master
    ports:
      - "50070:50070"
      - "8088:8088"
      - "19888:19888"
      - "4040:4040"
      - "8081:8081"
    volumes:
      - ${PWD}/working:/home/bigdata/working/
      - ${PWD}/hdfs-store:/home/bigdata/hadoop_store/hdfs/datanode
      - ${PWD}/.m2:/root/.m2/
    privileged: true
    stdin_open: true
    tty: true
    mem_reservation: 4G
    mem_limit: 8G
    environment:
      - WORK_DIR=/home/bigdata/working/
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ${PWD}/configs/migration:/docker-entrypoint-initdb.d

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
      #    ports:
      # commented port conflict with flink
      # - 8081:80 
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root


#  slave:
#    build:
#     context: .
#      dockerfile: Dockerfile
#    container_name: hadoop-slave
#    ports:
#      - "50070"
#      - "8088"
#      - "19888"
#    volumes:
#      - ${PWD}/working:/home/bigdata/hadoop/working/
#    privileged: true
#    stdin_open: true
#    tty: true
#    mem_reservation: 4G
#    mem_limit: 8G
#    environment:
#      - SERVICE_HOST_NAME=slave
#    depends_on:
#      - master


# ssh-copy-id -i $HOME/.ssh/id_rsa.pub root@slave
